apiVersion: v1
kind: Namespace
metadata:
  name: project-swan
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: project-swan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: project-swan
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader
  namespace: project-swan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: secret-reader
  namespace: project-swan
---
apiVersion: v1
kind: Secret
metadata:
  name: read-me
  namespace: project-swan
type: Opaque
stringData:
  token: some-demo-token-value
