apiVersion: v1
kind: Namespace
metadata:
  name: project-snake
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-content
  namespace: project-snake
data:
  index.html: "backend service"
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-0
  namespace: project-snake
  labels:
    app: backend
spec:
  containers:
  - name: nginx
    image: nginx:1-alpine
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: content
    configMap:
      name: backend-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db1-content
  namespace: project-snake
data:
  index.html: "database one"
---
apiVersion: v1
kind: Pod
metadata:
  name: db1-0
  namespace: project-snake
  labels:
    app: db1
spec:
  containers:
  - name: nginx
    image: nginx:1-alpine
    ports:
    - containerPort: 1111
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]
  volumes:
  - name: content
    configMap:
      name: db1-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db2-content
  namespace: project-snake
data:
  index.html: "database two"
---
apiVersion: v1
kind: Pod
metadata:
  name: db2-0
  namespace: project-snake
  labels:
    app: db2
spec:
  containers:
  - name: nginx
    image: nginx:1-alpine
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: content
    configMap:
      name: db2-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-content
  namespace: project-snake
data:
  index.html: "vault secret storage"
---
apiVersion: v1
kind: Pod
metadata:
  name: vault-0
  namespace: project-snake
  labels:
    app: vault
spec:
  containers:
  - name: nginx
    image: nginx:1-alpine
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: content
    configMap:
      name: vault-content
